% Prasanna Gandhi		Mar 29, 2000
% latex_fig.m
% This is a file to specify default attributes of figure for use in the latex 
% document. It can be used everytime the new figure is to be created
% 

set(0,'DefaultAxesFontSize',14, ...
'DefaultAxesFontWeight','factory', ...
'DefaultAxesLineWidth', 'factory', ...
'DefaultLineLineWidth', 'factory', ...
'DefaultAxesColor','white', ...
'DefaultAxesXColor','black', ...
'DefaultAxesYColor','black', ...
'DefaultAxesZColor','black', ...
'DefaultTextFontSize', 15, ... % To change the font size for the axis label.
'DefaultTextFontWeight', 'factory', ...
'DefaultTextColor','blue')
